### ISSUE TITLE
Directorio .idea

### ISSUE THREAD

**Issue by damiancastelao** [danielcastelao/mvc-anavalladaresg#1]
El directorio .idea no tiene que subirse.

- [x] Añádelo al .gitignore
- [x] Bórralo del repositorio

**Comment by anavalladaresg** [comment]
.idea eliminado.
![pasosParaEliminar idea](https://github.com/danielcastelao/mvc-anavalladaresg/assets/145323401/f41b65eb-9944-4926-9353-b0391c389b39)
